services:
  db:
    image: postgres:15-bookworm
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB_FILE=/run/secrets/POSTGRES_DB
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

    volumes:
      - prodigy_db:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - PRODIGY_KEY
        - PRODIGY_BASIC_AUTH_USER
        - PRODIGY_BASIC_AUTH_PASS
    ports:
      - "8080:8080"
    depends_on:
      - db

  json_editing_backend:
    build:
      context: .
      dockerfile: Dockerfile.json_editing
      secrets:
        - PRODIGY_KEY
        - PRODIGY_BASIC_AUTH_USER
        - PRODIGY_BASIC_AUTH_PASS
    ports:
      - "8081:8080"
    depends_on:
      - db

secrets:
  PRODIGY_KEY:
    file: ./secrets/PRODIGY_KEY
  PRODIGY_BASIC_AUTH_USER:
    file: ./secrets/PRODIGY_BASIC_AUTH_USER
  PRODIGY_BASIC_AUTH_PASS:
    file: ./secrets/PRODIGY_BASIC_AUTH_PASS
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  POSTGRES_DB:
    file: ./secrets/POSTGRES_DB

networks:
  default:
    driver: bridge

volumes:
  prodigy_db:
