services:
  db:
    image: postgres:15-bookworm
    ports:
      - 5432:5432
    volumes:
      - prodigy_db:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - PRODIGY_KEY
        - PRODIGY_BASIC_AUTH_USER
        - PRODIGY_BASIC_AUTH_PASS
    ports:
      - "8080:8080"
    depends_on:
      - db

  json_editing_backend:
    build:
      context: .
      dockerfile: Dockerfile.json_editing
      secrets:
        - PRODIGY_KEY
        - PRODIGY_BASIC_AUTH_USER
        - PRODIGY_BASIC_AUTH_PASS
    ports:
      - "8081:8080"
    depends_on:
      - db

secrets:
  PRODIGY_KEY:
    file: ./secrets/PRODIGY_KEY
  PRODIGY_BASIC_AUTH_USER:
    file: ./secrets/PRODIGY_BASIC_AUTH_USER
  PRODIGY_BASIC_AUTH_PASS:
    file: ./secrets/PRODIGY_BASIC_AUTH_PASS

networks:
  default:
    driver: bridge

volumes:
  prodigy_db:
