services:
  db:
    image: postgres:15-bookworm
    environment:
      POSTGRES_USER: prodigy_db_user
      POSTGRES_PASSWORD: ThisIsProdiGyDBPoswort
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - prodigy_db:/var/lib/postgresql/data/

  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    # volumes:
    #   - ./backend:/home/app/code
    depends_on:
      - db

networks:
  default:
    driver: bridge

volumes:
  prodigy_db:
