services:
  db:
    image: postgres:15-bookworm
    environment:
      POSTGRES_USER: prodigy_db_user
      POSTGRES_PASSWORD: ThisIsProdiGyDBPoswort
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - prodigy_db:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      secrets:
        - PRODIGY_KEY
        - PRODIGY_BASIC_AUTH_USER
        - PRODIGY_BASIC_AUTH_PASS
    ports:
      - "8080:8080"
    # volumes:
    #   - ./backend:/home/app/code
    depends_on:
      - db

secrets:
  PRODIGY_KEY:
    file: ./secrets/PRODIGY_KEY
  PRODIGY_BASIC_AUTH_USER:
    file: ./secrets/PRODIGY_BASIC_AUTH_USER
  PRODIGY_BASIC_AUTH_PASS:
    file: ./secrets/PRODIGY_BASIC_AUTH_PASS

networks:
  default:
    driver: bridge

volumes:
  prodigy_db:
